version: "3.8"

services:
  bombardier:
    image: ghcr.io/andrsuh/bombardier:${BOMBARDIER_VERSION:-latest}
    ports:
      - "1234:1234"
    restart: unless-stopped
    networks:
      - external_network

  prometheus:
    image: quay.io/prometheus/prometheus:v2.32.0
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=quipy
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  external_network: